### ISSUE TITLE
关于test命令

### ISSUE THREAD

**Issue by zhj12138** [jzplp/OSTEP-Answers#1]
你好，我想问问在习题中出现的这段代码：
```asm
sub  $1, %bx
test $0, %bx
jgt .top
```
其中的test指令的作用是什么，我感觉作者想表达的应该是cmp指令，即和0进行比较，比0大就继续循环。
但是根据我对test指令的了解，它是对两个参数进行与运算，可是任何数和0相与不都是0吗，这样对条件码的影响会和cmp相同吗？
我看到你的答案里好像也是按照cmp理解的，所以我有些困惑，是我对test指令理解错了吗？

**Comment by jzplp** [comment]
这是哪道习题？

**Comment by zhj12138** [comment]
@jzplp 这是线程那几个章节的模拟题里，一些`.s`文件中出现的代码(出现了很多次)

**Comment by jzplp** [comment]
哦哦，不同系统的的汇编代码是不一样的。这里仅仅是一种汇编的伪代码，不用纠结这个。

**Comment by zhj12138** [comment]
好的，谢啦
